CREATE DATABASE testDB;
USE testDB;
CREATE TABLE CALENDAR(MONTHS DATE NOT
 NULL;
 select * from calendar;
INSERT INTO CALENDAR(MONTHS) VALUES('2023-01-01');
INSERT INTO CALENDAR(MONTHS) VALUES('2023-02-01');
INSERT INTO CALENDAR(MONTHS) VALUES('2023-03-01');
INSERT INTO CALENDAR(MONTHS) VALUES('2023-04-01');
INSERT INTO CALENDAR(MONTHS) VALUES('2023-05-01');
INSERT INTO CALENDAR(MONTHS) VALUES('2023-06-01');
INSERT INTO CALENDAR(MONTHS) VALUES('2023-07-01');
INSERT INTO CALENDAR(MONTHS) VALUES('2023-08-01');
INSERT INTO CALENDAR(MONTHS) VALUES('2023-09-01');
INSERT INTO CALENDAR(MONTHS) VALUES('2023-10-01');
INSERT INTO CALENDAR(MONTHS) VALUES('2023-11-01');
INSERT INTO CALENDAR(MONTHS) VALUES('2023-12-04');
select * from calendar where months="2023-12-4";
show databases;
use edureka
alter database edureka modify name= kallu;
SELECT name From sys.databases

CREATE DATABASE testDB;
show databases
ALTER DATABASE testdb MODIFY NAME = "tutorialsDB";
SELECT * FROM sys.databases;
CREATE DATABASE testDB1;
CREATE DATABASE testDB2;
CREATE DATABASE testDB3;
CREATE TABLE KUTTAA(
   ID   INT              NOT NULL,
   NAME VARCHAR (20)     NOT NULL,
   AGE  INT              NOT NULL,
   ADDRESS  CHAR (25) ,
   DOB date,
   SALARY   DECIMAL (18, 2),       
   PRIMARY KEY (ID)
);
insert into KUTTA (ID,NAME,AGE,ADDRESS,DOB,SALARY) values (1001,"KAMALA",30,"NOIDA","1987-11-02",30000);
SELECT * FROM KUTTAA;
CREATE TABLE SALARY AS
SELECT ID, SALARY
FROM CUSTOMERS;
SELECT * FROM SALARY;
CREATE TABLE SALARY141 AS
SELECT ID, SALARY
FROM CUSTOMERS;
SELECT * FROM SALARY;
SHOW tables;
SELECT * FROM sys.tables;
INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'Ramesh', 32, 'Ahmedabad', 2000.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (2, 'Khilan', 25, 'Delhi', 1500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (3, 'kaushik', 23, 'Kota', 2000.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (4, 'Chaitali', 25, 'Mumbai', 6500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (5, 'Hardik', 27, 'Bhopal', 8500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (6, 'Komal', 22, 'MP', 4500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (7, 'Muffy', 24, 'Indore', 10000.00 );